version: "3.8"

services:
  frontend:
    build:
      context: ./react-appi  # Set the context to the frontend directory
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GDAL_CONFIG=/usr/bin/gdal-config
    volumes:
      - ./Backend:/Backend  # Optional: map local folder to container folder for local dev
    command: ["python", "main.py"]
